[package]
name = "have"
version = "0.1.0"
edition = "2018"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/have"
description = "Let any type have some fun"
license = "MIT"
categories = []
readme = "README.md"

[dependencies]
